version: 0.2

phases:
  install:
    commands:
      - wget -O ./cxcli.tar.gz "https://github.com/Checkmarx/ast-cli/releases/download/${CX_VERSION}/ast-cli_${CX_VERSION}_linux_x64.tar.gz"
      - tar xzvf ./cxcli.tar.gz
  build:
    commands:
      - ./cx scan create --project-name "exp-pnbxi-app202-user-data-channel-ms" --file-source "https://$GITHUB_TOKEN@github.com/joseca593/exp-pnbxi-app202-user-data-channel-ms" --branch "main" --report-format 'summaryHTML' --agent 'Github' --base-uri "$CX_BASE_URI" --tenant "$CX_TENANT" --client-id "$CX_CLIENT_ID" --client-secret "$CX_CLIENT_SECRET"
