version: 0.2

phases:
  install:
    commands:
      - wget -O ./cxcli.tar.gz "https://github.com/Checkmarx/ast-cli/releases/download/${CX_VERSION}/ast-cli_${CX_VERSION}_linux_x64.tar.gz"
      - tar xzvf ./cxcli.tar.gz
build:
    commands:
      - echo "Ejecutando análisis de seguridad con Checkmarx..."
      - ./cx scan create --project-name "$CX_PROJECT_NAME" \
        --repo "https://github.com/joseca593/exp-pnbxi-app202-user-data-channel-ms" --branch "main" \
        --client-id "$CX_CLIENT_ID" --client-secret "$CX_CLIENT_SECRET" \
        --tenant "$CX_TENANT" --base-uri "$CX_BASE_URI" \
        --report-format 'summaryHTML' --agent 'CodeBuild'
