version: 0.2

phases:
  install:
    commands:
      - wget -O ./cxcli.tar.gz "https://github.com/Checkmarx/ast-cli/releases/download/${CX_VERSION}/ast-cli_${CX_VERSION}_linux_x64.tar.gz"
      - tar xzvf ./cxcli.tar.gz
  build:
    commands:
      - echo "Iniciando el análisis con Checkmarx..."
      - ./cx scan --project-name "MiProyecto" --repo "https://github.com/joseca593/exp-pnbxi-app202-user-data-channel-ms" --branch "main"	  
